### ISSUE TITLE
-c参数没有起到作用？

### ISSUE THREAD

**Issue by cwkiller** [uknowsec/SauronEye-Modify#1]
![image](https://user-images.githubusercontent.com/19302055/97033708-57f6c580-1596-11eb-9cfe-963285db4844.png)
-c选项的参数为啥到-f里面了然后Containing:为空

**Comment by uknowsec** [comment]
参考原项目 ` 
SauronEye.exe --directories C:\ \\SOMENETWORKDRIVE\C$ --filetypes .txt .bat .docx .conf --contents --keywords password pass* `

**Comment by uknowsec** [comment]
https://github.com/vivami/SauronEye.git
